### PR TITLE
Add module-info.class to artifact

### PR DESCRIPTION
**Pull request by Glavo**
Currently this library uses `Automatic-Module-Name` to specify the name of the module, but unfortunately this strategy does not always work: `jlink` tool does not support automatic modules, and 
 `annotations-java5` artifact uses the invalid module name `org.jetbrains.annotations-java5.

Using explicit module can solve these problems, but the higher version of javac does not support release 5, so I just provide the pre-purchased module-info.class as a resource file.

### CODE REVIEW

**Comment by amaembo** [comment]
I fixed the invalid module name for java5, replacing `-` with `_`. I'm not sure, however, that it's a good idea to store precompiled binary `module-info.class` here. Btw is it really necessary to package JetBrains annotations via jlink? If you are building the standalone product probably you can omit the static analysis annotations. They are not reflectively accessible anyway.

**Comment by Glavo** [comment]
I agree with you that this annotation library does not seem to need to be explicitly modular.
But I also have a suggestion, I hope that the module names of java5 and java8 will be the same. Using different names is meaningless and confusing for users.

**Comment by xzel23** [comment]
> If you are building the standalone product probably you can omit the static analysis annotations.

How would I do that when the annotations are used in a jar that I rely on?

**Comment by JojOatXGME** [comment]
> > If you are building the standalone product probably you can omit the static analysis annotations.
> 
> How would I do that when the annotations are used in a jar that I rely on?

Depends on your build tool. For Gradle, you can find more information here: [Downgrading versions and excluding dependencies](https://docs.gradle.org/current/userguide/dependency_downgrade_and_exclude.html). I don't know about Maven and other tools.

**Comment by marcelbaumann** [comment]
Support for module-info would allow the simpler build of module-based applications. Given that Java 9 is quite old, it is time to finally support modules.
And JDK 16 seems to pickier and generate warnings "warning: requires directive for an automatic module
    requires static org.jetbrains.annotations;"

**Comment by amaembo** [comment]
Implemented separately, via e1f9f35d61521652abcb65d29cd3637ed4a344a1

**Pull request closed without merging**
